//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace DataBase.MonitorService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MonitorServiceSoap", Namespace="http://www.farshine.com/")]
    public partial class MonitorService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetGuiZeListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetYuFaInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendYuFaInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBoxSetInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGroupSetInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllBoxInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBoxShowMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllCardInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBarcodeMuBanListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMuBanInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendBoxStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserGetLetterOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserGetLetter_RecordOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserGetLetter_SetPicOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserGetLetter_ReportOperationCompleted;
        
        private System.Threading.SendOrPostCallback PrintUserReturnLetterOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MonitorService() {
            this.Url = global::DataBase.Properties.Settings.Default.DataBase_MonitorService_MonitorService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetGuiZeListCompletedEventHandler GetGuiZeListCompleted;
        
        /// <remarks/>
        public event GetYuFaInfoCompletedEventHandler GetYuFaInfoCompleted;
        
        /// <remarks/>
        public event SendYuFaInfoCompletedEventHandler SendYuFaInfoCompleted;
        
        /// <remarks/>
        public event GetBoxSetInfoCompletedEventHandler GetBoxSetInfoCompleted;
        
        /// <remarks/>
        public event GetGroupSetInfoCompletedEventHandler GetGroupSetInfoCompleted;
        
        /// <remarks/>
        public event GetAllBoxInfoCompletedEventHandler GetAllBoxInfoCompleted;
        
        /// <remarks/>
        public event GetBoxShowMessageCompletedEventHandler GetBoxShowMessageCompleted;
        
        /// <remarks/>
        public event GetAllCardInfoCompletedEventHandler GetAllCardInfoCompleted;
        
        /// <remarks/>
        public event GetBarcodeMuBanListCompletedEventHandler GetBarcodeMuBanListCompleted;
        
        /// <remarks/>
        public event GetMuBanInfoCompletedEventHandler GetMuBanInfoCompleted;
        
        /// <remarks/>
        public event SendBoxStatusCompletedEventHandler SendBoxStatusCompleted;
        
        /// <remarks/>
        public event UserGetLetterCompletedEventHandler UserGetLetterCompleted;
        
        /// <remarks/>
        public event UserGetLetter_RecordCompletedEventHandler UserGetLetter_RecordCompleted;
        
        /// <remarks/>
        public event UserGetLetter_SetPicCompletedEventHandler UserGetLetter_SetPicCompleted;
        
        /// <remarks/>
        public event UserGetLetter_ReportCompletedEventHandler UserGetLetter_ReportCompleted;
        
        /// <remarks/>
        public event PrintUserReturnLetterCompletedEventHandler PrintUserReturnLetterCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.farshine.com/GetGuiZeList", RequestNamespace="http://www.farshine.com/", ResponseNamespace="http://www.farshine.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GuiZeListClass[] GetGuiZeList(int MinBoxId, int MaxBoxId) {
            object[] results = this.Invoke("GetGuiZeList", new object[] {
                        MinBoxId,
                        MaxBoxId});
            return ((GuiZeListClass[])(results[0]));
        }
        
        /// <remarks/>
        public void GetGuiZeListAsync(int MinBoxId, int MaxBoxId) {
            this.GetGuiZeListAsync(MinBoxId, MaxBoxId, null);
        }
        
        /// <remarks/>
        public void GetGuiZeListAsync(int MinBoxId, int MaxBoxId, object userState) {
            if ((this.GetGuiZeListOperationCompleted == null)) {
                this.GetGuiZeListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGuiZeListOperationCompleted);
            }
            this.InvokeAsync("GetGuiZeList", new object[] {
                        MinBoxId,
                        MaxBoxId}, this.GetGuiZeListOperationCompleted, userState);
        }
        
        private void OnGetGuiZeListOperationCompleted(object arg) {
            if ((this.GetGuiZeListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGuiZeListCompleted(this, new GetGuiZeListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.farshine.com/GetYuFaInfo", RequestNamespace="http://www.farshine.com/", ResponseNamespace="http://www.farshine.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public YuFaClass[] GetYuFaInfo(string LastYFBiaoZhi, int MinBoxId, int MaxBoxId) {
            object[] results = this.Invoke("GetYuFaInfo", new object[] {
                        LastYFBiaoZhi,
                        MinBoxId,
                        MaxBoxId});
            return ((YuFaClass[])(results[0]));
        }
        
        /// <remarks/>
        public void GetYuFaInfoAsync(string LastYFBiaoZhi, int MinBoxId, int MaxBoxId) {
            this.GetYuFaInfoAsync(LastYFBiaoZhi, MinBoxId, MaxBoxId, null);
        }
        
        /// <remarks/>
        public void GetYuFaInfoAsync(string LastYFBiaoZhi, int MinBoxId, int MaxBoxId, object userState) {
            if ((this.GetYuFaInfoOperationCompleted == null)) {
                this.GetYuFaInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetYuFaInfoOperationCompleted);
            }
            this.InvokeAsync("GetYuFaInfo", new object[] {
                        LastYFBiaoZhi,
                        MinBoxId,
                        MaxBoxId}, this.GetYuFaInfoOperationCompleted, userState);
        }
        
        private void OnGetYuFaInfoOperationCompleted(object arg) {
            if ((this.GetYuFaInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetYuFaInfoCompleted(this, new GetYuFaInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.farshine.com/SendYuFaInfo", RequestNamespace="http://www.farshine.com/", ResponseNamespace="http://www.farshine.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SendYuFaInfo(ref YuFaClass infos) {
            object[] results = this.Invoke("SendYuFaInfo", new object[] {
                        infos});
            infos = ((YuFaClass)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SendYuFaInfoAsync(YuFaClass infos) {
            this.SendYuFaInfoAsync(infos, null);
        }
        
        /// <remarks/>
        public void SendYuFaInfoAsync(YuFaClass infos, object userState) {
            if ((this.SendYuFaInfoOperationCompleted == null)) {
                this.SendYuFaInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendYuFaInfoOperationCompleted);
            }
            this.InvokeAsync("SendYuFaInfo", new object[] {
                        infos}, this.SendYuFaInfoOperationCompleted, userState);
        }
        
        private void OnSendYuFaInfoOperationCompleted(object arg) {
            if ((this.SendYuFaInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendYuFaInfoCompleted(this, new SendYuFaInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.farshine.com/GetBoxSetInfo", RequestNamespace="http://www.farshine.com/", ResponseNamespace="http://www.farshine.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BoxSetInfoClass[] GetBoxSetInfo() {
            object[] results = this.Invoke("GetBoxSetInfo", new object[0]);
            return ((BoxSetInfoClass[])(results[0]));
        }
        
        /// <remarks/>
        public void GetBoxSetInfoAsync() {
            this.GetBoxSetInfoAsync(null);
        }
        
        /// <remarks/>
        public void GetBoxSetInfoAsync(object userState) {
            if ((this.GetBoxSetInfoOperationCompleted == null)) {
                this.GetBoxSetInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBoxSetInfoOperationCompleted);
            }
            this.InvokeAsync("GetBoxSetInfo", new object[0], this.GetBoxSetInfoOperationCompleted, userState);
        }
        
        private void OnGetBoxSetInfoOperationCompleted(object arg) {
            if ((this.GetBoxSetInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBoxSetInfoCompleted(this, new GetBoxSetInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.farshine.com/GetGroupSetInfo", RequestNamespace="http://www.farshine.com/", ResponseNamespace="http://www.farshine.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GroupSetInfoClass[] GetGroupSetInfo() {
            object[] results = this.Invoke("GetGroupSetInfo", new object[0]);
            return ((GroupSetInfoClass[])(results[0]));
        }
        
        /// <remarks/>
        public void GetGroupSetInfoAsync() {
            this.GetGroupSetInfoAsync(null);
        }
        
        /// <remarks/>
        public void GetGroupSetInfoAsync(object userState) {
            if ((this.GetGroupSetInfoOperationCompleted == null)) {
                this.GetGroupSetInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGroupSetInfoOperationCompleted);
            }
            this.InvokeAsync("GetGroupSetInfo", new object[0], this.GetGroupSetInfoOperationCompleted, userState);
        }
        
        private void OnGetGroupSetInfoOperationCompleted(object arg) {
            if ((this.GetGroupSetInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGroupSetInfoCompleted(this, new GetGroupSetInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.farshine.com/GetAllBoxInfo", RequestNamespace="http://www.farshine.com/", ResponseNamespace="http://www.farshine.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BoxInfo[] GetAllBoxInfo(int MinBoxId, int MaxBoxId) {
            object[] results = this.Invoke("GetAllBoxInfo", new object[] {
                        MinBoxId,
                        MaxBoxId});
            return ((BoxInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllBoxInfoAsync(int MinBoxId, int MaxBoxId) {
            this.GetAllBoxInfoAsync(MinBoxId, MaxBoxId, null);
        }
        
        /// <remarks/>
        public void GetAllBoxInfoAsync(int MinBoxId, int MaxBoxId, object userState) {
            if ((this.GetAllBoxInfoOperationCompleted == null)) {
                this.GetAllBoxInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllBoxInfoOperationCompleted);
            }
            this.InvokeAsync("GetAllBoxInfo", new object[] {
                        MinBoxId,
                        MaxBoxId}, this.GetAllBoxInfoOperationCompleted, userState);
        }
        
        private void OnGetAllBoxInfoOperationCompleted(object arg) {
            if ((this.GetAllBoxInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllBoxInfoCompleted(this, new GetAllBoxInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.farshine.com/GetBoxShowMessage", RequestNamespace="http://www.farshine.com/", ResponseNamespace="http://www.farshine.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ClassBoxShowMessage[] GetBoxShowMessage(int MinBoxId, int MaxBoxId) {
            object[] results = this.Invoke("GetBoxShowMessage", new object[] {
                        MinBoxId,
                        MaxBoxId});
            return ((ClassBoxShowMessage[])(results[0]));
        }
        
        /// <remarks/>
        public void GetBoxShowMessageAsync(int MinBoxId, int MaxBoxId) {
            this.GetBoxShowMessageAsync(MinBoxId, MaxBoxId, null);
        }
        
        /// <remarks/>
        public void GetBoxShowMessageAsync(int MinBoxId, int MaxBoxId, object userState) {
            if ((this.GetBoxShowMessageOperationCompleted == null)) {
                this.GetBoxShowMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBoxShowMessageOperationCompleted);
            }
            this.InvokeAsync("GetBoxShowMessage", new object[] {
                        MinBoxId,
                        MaxBoxId}, this.GetBoxShowMessageOperationCompleted, userState);
        }
        
        private void OnGetBoxShowMessageOperationCompleted(object arg) {
            if ((this.GetBoxShowMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBoxShowMessageCompleted(this, new GetBoxShowMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.farshine.com/GetAllCardInfo", RequestNamespace="http://www.farshine.com/", ResponseNamespace="http://www.farshine.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CardInfoClass[] GetAllCardInfo(int MinBoxId, int MaxBoxId) {
            object[] results = this.Invoke("GetAllCardInfo", new object[] {
                        MinBoxId,
                        MaxBoxId});
            return ((CardInfoClass[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllCardInfoAsync(int MinBoxId, int MaxBoxId) {
            this.GetAllCardInfoAsync(MinBoxId, MaxBoxId, null);
        }
        
        /// <remarks/>
        public void GetAllCardInfoAsync(int MinBoxId, int MaxBoxId, object userState) {
            if ((this.GetAllCardInfoOperationCompleted == null)) {
                this.GetAllCardInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllCardInfoOperationCompleted);
            }
            this.InvokeAsync("GetAllCardInfo", new object[] {
                        MinBoxId,
                        MaxBoxId}, this.GetAllCardInfoOperationCompleted, userState);
        }
        
        private void OnGetAllCardInfoOperationCompleted(object arg) {
            if ((this.GetAllCardInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllCardInfoCompleted(this, new GetAllCardInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.farshine.com/GetBarcodeMuBanList", RequestNamespace="http://www.farshine.com/", ResponseNamespace="http://www.farshine.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ClassBarcodeMuBanList[] GetBarcodeMuBanList(string FullBarcode) {
            object[] results = this.Invoke("GetBarcodeMuBanList", new object[] {
                        FullBarcode});
            return ((ClassBarcodeMuBanList[])(results[0]));
        }
        
        /// <remarks/>
        public void GetBarcodeMuBanListAsync(string FullBarcode) {
            this.GetBarcodeMuBanListAsync(FullBarcode, null);
        }
        
        /// <remarks/>
        public void GetBarcodeMuBanListAsync(string FullBarcode, object userState) {
            if ((this.GetBarcodeMuBanListOperationCompleted == null)) {
                this.GetBarcodeMuBanListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBarcodeMuBanListOperationCompleted);
            }
            this.InvokeAsync("GetBarcodeMuBanList", new object[] {
                        FullBarcode}, this.GetBarcodeMuBanListOperationCompleted, userState);
        }
        
        private void OnGetBarcodeMuBanListOperationCompleted(object arg) {
            if ((this.GetBarcodeMuBanListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBarcodeMuBanListCompleted(this, new GetBarcodeMuBanListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.farshine.com/GetMuBanInfo", RequestNamespace="http://www.farshine.com/", ResponseNamespace="http://www.farshine.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public YuFaClass GetMuBanInfo(string MuBanID) {
            object[] results = this.Invoke("GetMuBanInfo", new object[] {
                        MuBanID});
            return ((YuFaClass)(results[0]));
        }
        
        /// <remarks/>
        public void GetMuBanInfoAsync(string MuBanID) {
            this.GetMuBanInfoAsync(MuBanID, null);
        }
        
        /// <remarks/>
        public void GetMuBanInfoAsync(string MuBanID, object userState) {
            if ((this.GetMuBanInfoOperationCompleted == null)) {
                this.GetMuBanInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMuBanInfoOperationCompleted);
            }
            this.InvokeAsync("GetMuBanInfo", new object[] {
                        MuBanID}, this.GetMuBanInfoOperationCompleted, userState);
        }
        
        private void OnGetMuBanInfoOperationCompleted(object arg) {
            if ((this.GetMuBanInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMuBanInfoCompleted(this, new GetMuBanInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.farshine.com/SendBoxStatus", RequestNamespace="http://www.farshine.com/", ResponseNamespace="http://www.farshine.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SendBoxStatus(BoxStatus box) {
            object[] results = this.Invoke("SendBoxStatus", new object[] {
                        box});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SendBoxStatusAsync(BoxStatus box) {
            this.SendBoxStatusAsync(box, null);
        }
        
        /// <remarks/>
        public void SendBoxStatusAsync(BoxStatus box, object userState) {
            if ((this.SendBoxStatusOperationCompleted == null)) {
                this.SendBoxStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendBoxStatusOperationCompleted);
            }
            this.InvokeAsync("SendBoxStatus", new object[] {
                        box}, this.SendBoxStatusOperationCompleted, userState);
        }
        
        private void OnSendBoxStatusOperationCompleted(object arg) {
            if ((this.SendBoxStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendBoxStatusCompleted(this, new SendBoxStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.farshine.com/UserGetLetter", RequestNamespace="http://www.farshine.com/", ResponseNamespace="http://www.farshine.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UserGetLetter(int BoxNO, string UserCardId, string SendTime, string PicData, bool PrintSendList, bool PrintReceiveList) {
            object[] results = this.Invoke("UserGetLetter", new object[] {
                        BoxNO,
                        UserCardId,
                        SendTime,
                        PicData,
                        PrintSendList,
                        PrintReceiveList});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UserGetLetterAsync(int BoxNO, string UserCardId, string SendTime, string PicData, bool PrintSendList, bool PrintReceiveList) {
            this.UserGetLetterAsync(BoxNO, UserCardId, SendTime, PicData, PrintSendList, PrintReceiveList, null);
        }
        
        /// <remarks/>
        public void UserGetLetterAsync(int BoxNO, string UserCardId, string SendTime, string PicData, bool PrintSendList, bool PrintReceiveList, object userState) {
            if ((this.UserGetLetterOperationCompleted == null)) {
                this.UserGetLetterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserGetLetterOperationCompleted);
            }
            this.InvokeAsync("UserGetLetter", new object[] {
                        BoxNO,
                        UserCardId,
                        SendTime,
                        PicData,
                        PrintSendList,
                        PrintReceiveList}, this.UserGetLetterOperationCompleted, userState);
        }
        
        private void OnUserGetLetterOperationCompleted(object arg) {
            if ((this.UserGetLetterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserGetLetterCompleted(this, new UserGetLetterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.farshine.com/UserGetLetter_Record", RequestNamespace="http://www.farshine.com/", ResponseNamespace="http://www.farshine.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UserGetLetter_Record(int BoxNO, string UserCardId, string SendTime) {
            object[] results = this.Invoke("UserGetLetter_Record", new object[] {
                        BoxNO,
                        UserCardId,
                        SendTime});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void UserGetLetter_RecordAsync(int BoxNO, string UserCardId, string SendTime) {
            this.UserGetLetter_RecordAsync(BoxNO, UserCardId, SendTime, null);
        }
        
        /// <remarks/>
        public void UserGetLetter_RecordAsync(int BoxNO, string UserCardId, string SendTime, object userState) {
            if ((this.UserGetLetter_RecordOperationCompleted == null)) {
                this.UserGetLetter_RecordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserGetLetter_RecordOperationCompleted);
            }
            this.InvokeAsync("UserGetLetter_Record", new object[] {
                        BoxNO,
                        UserCardId,
                        SendTime}, this.UserGetLetter_RecordOperationCompleted, userState);
        }
        
        private void OnUserGetLetter_RecordOperationCompleted(object arg) {
            if ((this.UserGetLetter_RecordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserGetLetter_RecordCompleted(this, new UserGetLetter_RecordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.farshine.com/UserGetLetter_SetPic", RequestNamespace="http://www.farshine.com/", ResponseNamespace="http://www.farshine.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UserGetLetter_SetPic(int 取件记录ID, string PicData) {
            object[] results = this.Invoke("UserGetLetter_SetPic", new object[] {
                        取件记录ID,
                        PicData});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UserGetLetter_SetPicAsync(int 取件记录ID, string PicData) {
            this.UserGetLetter_SetPicAsync(取件记录ID, PicData, null);
        }
        
        /// <remarks/>
        public void UserGetLetter_SetPicAsync(int 取件记录ID, string PicData, object userState) {
            if ((this.UserGetLetter_SetPicOperationCompleted == null)) {
                this.UserGetLetter_SetPicOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserGetLetter_SetPicOperationCompleted);
            }
            this.InvokeAsync("UserGetLetter_SetPic", new object[] {
                        取件记录ID,
                        PicData}, this.UserGetLetter_SetPicOperationCompleted, userState);
        }
        
        private void OnUserGetLetter_SetPicOperationCompleted(object arg) {
            if ((this.UserGetLetter_SetPicCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserGetLetter_SetPicCompleted(this, new UserGetLetter_SetPicCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.farshine.com/UserGetLetter_Report", RequestNamespace="http://www.farshine.com/", ResponseNamespace="http://www.farshine.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserGetLetterReturnClass UserGetLetter_Report(int 取件记录ID, string LocationName, bool PrintSendList, bool PrintReceiveList) {
            object[] results = this.Invoke("UserGetLetter_Report", new object[] {
                        取件记录ID,
                        LocationName,
                        PrintSendList,
                        PrintReceiveList});
            return ((UserGetLetterReturnClass)(results[0]));
        }
        
        /// <remarks/>
        public void UserGetLetter_ReportAsync(int 取件记录ID, string LocationName, bool PrintSendList, bool PrintReceiveList) {
            this.UserGetLetter_ReportAsync(取件记录ID, LocationName, PrintSendList, PrintReceiveList, null);
        }
        
        /// <remarks/>
        public void UserGetLetter_ReportAsync(int 取件记录ID, string LocationName, bool PrintSendList, bool PrintReceiveList, object userState) {
            if ((this.UserGetLetter_ReportOperationCompleted == null)) {
                this.UserGetLetter_ReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserGetLetter_ReportOperationCompleted);
            }
            this.InvokeAsync("UserGetLetter_Report", new object[] {
                        取件记录ID,
                        LocationName,
                        PrintSendList,
                        PrintReceiveList}, this.UserGetLetter_ReportOperationCompleted, userState);
        }
        
        private void OnUserGetLetter_ReportOperationCompleted(object arg) {
            if ((this.UserGetLetter_ReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserGetLetter_ReportCompleted(this, new UserGetLetter_ReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.farshine.com/PrintUserReturnLetter", RequestNamespace="http://www.farshine.com/", ResponseNamespace="http://www.farshine.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserGetLetterReturnClass PrintUserReturnLetter(string UserCardId) {
            object[] results = this.Invoke("PrintUserReturnLetter", new object[] {
                        UserCardId});
            return ((UserGetLetterReturnClass)(results[0]));
        }
        
        /// <remarks/>
        public void PrintUserReturnLetterAsync(string UserCardId) {
            this.PrintUserReturnLetterAsync(UserCardId, null);
        }
        
        /// <remarks/>
        public void PrintUserReturnLetterAsync(string UserCardId, object userState) {
            if ((this.PrintUserReturnLetterOperationCompleted == null)) {
                this.PrintUserReturnLetterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPrintUserReturnLetterOperationCompleted);
            }
            this.InvokeAsync("PrintUserReturnLetter", new object[] {
                        UserCardId}, this.PrintUserReturnLetterOperationCompleted, userState);
        }
        
        private void OnPrintUserReturnLetterOperationCompleted(object arg) {
            if ((this.PrintUserReturnLetterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PrintUserReturnLetterCompleted(this, new PrintUserReturnLetterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.farshine.com/")]
    public partial class GuiZeListClass {
        
        private int gZBiaoZhiField;
        
        private string nameField;
        
        private int barTypeField;
        
        private bool hasZhiTouField;
        
        private bool canCheckRcvUnitField;
        
        private bool hasPuFaField;
        
        private bool hasMobanField;
        
        private bool canRepeatField;
        
        /// <remarks/>
        public int GZBiaoZhi {
            get {
                return this.gZBiaoZhiField;
            }
            set {
                this.gZBiaoZhiField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int BarType {
            get {
                return this.barTypeField;
            }
            set {
                this.barTypeField = value;
            }
        }
        
        /// <remarks/>
        public bool HasZhiTou {
            get {
                return this.hasZhiTouField;
            }
            set {
                this.hasZhiTouField = value;
            }
        }
        
        /// <remarks/>
        public bool CanCheckRcvUnit {
            get {
                return this.canCheckRcvUnitField;
            }
            set {
                this.canCheckRcvUnitField = value;
            }
        }
        
        /// <remarks/>
        public bool HasPuFa {
            get {
                return this.hasPuFaField;
            }
            set {
                this.hasPuFaField = value;
            }
        }
        
        /// <remarks/>
        public bool HasMoban {
            get {
                return this.hasMobanField;
            }
            set {
                this.hasMobanField = value;
            }
        }
        
        /// <remarks/>
        public bool CanRepeat {
            get {
                return this.canRepeatField;
            }
            set {
                this.canRepeatField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.farshine.com/")]
    public partial class UserGetLetterReturnClass {
        
        private bool bSuccessField;
        
        private bool bPrintSendReportField;
        
        private string szSendTemplateFileNameField;
        
        private string szSendXmlDataField;
        
        private bool bPrintRecvReportField;
        
        private string szRecvTemplateFileNameField;
        
        private string szRecvXmlDataField;
        
        /// <remarks/>
        public bool bSuccess {
            get {
                return this.bSuccessField;
            }
            set {
                this.bSuccessField = value;
            }
        }
        
        /// <remarks/>
        public bool bPrintSendReport {
            get {
                return this.bPrintSendReportField;
            }
            set {
                this.bPrintSendReportField = value;
            }
        }
        
        /// <remarks/>
        public string szSendTemplateFileName {
            get {
                return this.szSendTemplateFileNameField;
            }
            set {
                this.szSendTemplateFileNameField = value;
            }
        }
        
        /// <remarks/>
        public string szSendXmlData {
            get {
                return this.szSendXmlDataField;
            }
            set {
                this.szSendXmlDataField = value;
            }
        }
        
        /// <remarks/>
        public bool bPrintRecvReport {
            get {
                return this.bPrintRecvReportField;
            }
            set {
                this.bPrintRecvReportField = value;
            }
        }
        
        /// <remarks/>
        public string szRecvTemplateFileName {
            get {
                return this.szRecvTemplateFileNameField;
            }
            set {
                this.szRecvTemplateFileNameField = value;
            }
        }
        
        /// <remarks/>
        public string szRecvXmlData {
            get {
                return this.szRecvXmlDataField;
            }
            set {
                this.szRecvXmlDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.farshine.com/")]
    public partial class BoxStatus {
        
        private int boxNoField;
        
        private bool isFrontField;
        
        private bool lampJiJianField;
        
        private bool lampYiQuField;
        
        private bool lampCuoWuField;
        
        private int doorStatusField;
        
        private int gateStatusField;
        
        private bool frontGDField;
        
        private bool backGDField;
        
        private bool fullGDField;
        
        private bool clearGDField;
        
        private bool chufaGDField;
        
        /// <remarks/>
        public int BoxNo {
            get {
                return this.boxNoField;
            }
            set {
                this.boxNoField = value;
            }
        }
        
        /// <remarks/>
        public bool IsFront {
            get {
                return this.isFrontField;
            }
            set {
                this.isFrontField = value;
            }
        }
        
        /// <remarks/>
        public bool LampJiJian {
            get {
                return this.lampJiJianField;
            }
            set {
                this.lampJiJianField = value;
            }
        }
        
        /// <remarks/>
        public bool LampYiQu {
            get {
                return this.lampYiQuField;
            }
            set {
                this.lampYiQuField = value;
            }
        }
        
        /// <remarks/>
        public bool LampCuoWu {
            get {
                return this.lampCuoWuField;
            }
            set {
                this.lampCuoWuField = value;
            }
        }
        
        /// <remarks/>
        public int DoorStatus {
            get {
                return this.doorStatusField;
            }
            set {
                this.doorStatusField = value;
            }
        }
        
        /// <remarks/>
        public int GateStatus {
            get {
                return this.gateStatusField;
            }
            set {
                this.gateStatusField = value;
            }
        }
        
        /// <remarks/>
        public bool FrontGD {
            get {
                return this.frontGDField;
            }
            set {
                this.frontGDField = value;
            }
        }
        
        /// <remarks/>
        public bool BackGD {
            get {
                return this.backGDField;
            }
            set {
                this.backGDField = value;
            }
        }
        
        /// <remarks/>
        public bool FullGD {
            get {
                return this.fullGDField;
            }
            set {
                this.fullGDField = value;
            }
        }
        
        /// <remarks/>
        public bool ClearGD {
            get {
                return this.clearGDField;
            }
            set {
                this.clearGDField = value;
            }
        }
        
        /// <remarks/>
        public bool ChufaGD {
            get {
                return this.chufaGDField;
            }
            set {
                this.chufaGDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.farshine.com/")]
    public partial class ClassBarcodeMuBanList {
        
        private string 模板标识Field;
        
        private string 模板名称Field;
        
        private string 模板详情Field;
        
        /// <remarks/>
        public string 模板标识 {
            get {
                return this.模板标识Field;
            }
            set {
                this.模板标识Field = value;
            }
        }
        
        /// <remarks/>
        public string 模板名称 {
            get {
                return this.模板名称Field;
            }
            set {
                this.模板名称Field = value;
            }
        }
        
        /// <remarks/>
        public string 模板详情 {
            get {
                return this.模板详情Field;
            }
            set {
                this.模板详情Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.farshine.com/")]
    public partial class CardInfoClass {
        
        private int idField;
        
        private int yanZhengTypeField;
        
        private string cardNOField;
        
        private int cardtypeField;
        
        private string unitNameField;
        
        private string userNameField;
        
        private int cardPrintTypeField;
        
        private int boxNOField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int YanZhengType {
            get {
                return this.yanZhengTypeField;
            }
            set {
                this.yanZhengTypeField = value;
            }
        }
        
        /// <remarks/>
        public string CardNO {
            get {
                return this.cardNOField;
            }
            set {
                this.cardNOField = value;
            }
        }
        
        /// <remarks/>
        public int Cardtype {
            get {
                return this.cardtypeField;
            }
            set {
                this.cardtypeField = value;
            }
        }
        
        /// <remarks/>
        public string UnitName {
            get {
                return this.unitNameField;
            }
            set {
                this.unitNameField = value;
            }
        }
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public int CardPrintType {
            get {
                return this.cardPrintTypeField;
            }
            set {
                this.cardPrintTypeField = value;
            }
        }
        
        /// <remarks/>
        public int boxNO {
            get {
                return this.boxNOField;
            }
            set {
                this.boxNOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.farshine.com/")]
    public partial class ClassBoxShowMessage {
        
        private int 逻辑箱号Field;
        
        private string 出差信息Field;
        
        /// <remarks/>
        public int 逻辑箱号 {
            get {
                return this.逻辑箱号Field;
            }
            set {
                this.逻辑箱号Field = value;
            }
        }
        
        /// <remarks/>
        public string 出差信息 {
            get {
                return this.出差信息Field;
            }
            set {
                this.出差信息Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.farshine.com/")]
    public partial class BoxInfo {
        
        private int boxNOField;
        
        private string unitCodeField;
        
        private string boxShowNameField;
        
        private string boxShowFullNameField;
        
        private bool isQingTuiXiangField;
        
        private int sendCountField;
        
        private bool hasJiJianField;
        
        private int dengJiCountField;
        
        private int dengJiJJCountField;
        
        private int boxPropertyField;
        
        /// <remarks/>
        public int BoxNO {
            get {
                return this.boxNOField;
            }
            set {
                this.boxNOField = value;
            }
        }
        
        /// <remarks/>
        public string UnitCode {
            get {
                return this.unitCodeField;
            }
            set {
                this.unitCodeField = value;
            }
        }
        
        /// <remarks/>
        public string BoxShowName {
            get {
                return this.boxShowNameField;
            }
            set {
                this.boxShowNameField = value;
            }
        }
        
        /// <remarks/>
        public string BoxShowFullName {
            get {
                return this.boxShowFullNameField;
            }
            set {
                this.boxShowFullNameField = value;
            }
        }
        
        /// <remarks/>
        public bool IsQingTuiXiang {
            get {
                return this.isQingTuiXiangField;
            }
            set {
                this.isQingTuiXiangField = value;
            }
        }
        
        /// <remarks/>
        public int SendCount {
            get {
                return this.sendCountField;
            }
            set {
                this.sendCountField = value;
            }
        }
        
        /// <remarks/>
        public bool HasJiJian {
            get {
                return this.hasJiJianField;
            }
            set {
                this.hasJiJianField = value;
            }
        }
        
        /// <remarks/>
        public int DengJiCount {
            get {
                return this.dengJiCountField;
            }
            set {
                this.dengJiCountField = value;
            }
        }
        
        /// <remarks/>
        public int DengJiJJCount {
            get {
                return this.dengJiJJCountField;
            }
            set {
                this.dengJiJJCountField = value;
            }
        }
        
        /// <remarks/>
        public int BoxProperty {
            get {
                return this.boxPropertyField;
            }
            set {
                this.boxPropertyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.farshine.com/")]
    public partial class GroupSetInfoClass {
        
        private string groupNameField;
        
        private string groupFrontScanBNField;
        
        private string groupFrontCardBNField;
        
        private string groupFrontShowBNField;
        
        private string groupFrontSoundBNField;
        
        private string groupFrontZhiJingMaiBNField;
        
        private string groupFrontSheXiangTouBNField;
        
        private string groupBackScanBNField;
        
        private string groupBackCardBNField;
        
        private string groupBackShowBNField;
        
        private string groupBackSoundBNField;
        
        private string groupBackZhiJingMaiBNField;
        
        private string groupBackSheXiangTouBNField;
        
        private string printerNameField;
        
        private string[] boxArrayField;
        
        private string[] groupNameArrayField;
        
        /// <remarks/>
        public string GroupName {
            get {
                return this.groupNameField;
            }
            set {
                this.groupNameField = value;
            }
        }
        
        /// <remarks/>
        public string GroupFrontScanBN {
            get {
                return this.groupFrontScanBNField;
            }
            set {
                this.groupFrontScanBNField = value;
            }
        }
        
        /// <remarks/>
        public string GroupFrontCardBN {
            get {
                return this.groupFrontCardBNField;
            }
            set {
                this.groupFrontCardBNField = value;
            }
        }
        
        /// <remarks/>
        public string GroupFrontShowBN {
            get {
                return this.groupFrontShowBNField;
            }
            set {
                this.groupFrontShowBNField = value;
            }
        }
        
        /// <remarks/>
        public string GroupFrontSoundBN {
            get {
                return this.groupFrontSoundBNField;
            }
            set {
                this.groupFrontSoundBNField = value;
            }
        }
        
        /// <remarks/>
        public string GroupFrontZhiJingMaiBN {
            get {
                return this.groupFrontZhiJingMaiBNField;
            }
            set {
                this.groupFrontZhiJingMaiBNField = value;
            }
        }
        
        /// <remarks/>
        public string GroupFrontSheXiangTouBN {
            get {
                return this.groupFrontSheXiangTouBNField;
            }
            set {
                this.groupFrontSheXiangTouBNField = value;
            }
        }
        
        /// <remarks/>
        public string GroupBackScanBN {
            get {
                return this.groupBackScanBNField;
            }
            set {
                this.groupBackScanBNField = value;
            }
        }
        
        /// <remarks/>
        public string GroupBackCardBN {
            get {
                return this.groupBackCardBNField;
            }
            set {
                this.groupBackCardBNField = value;
            }
        }
        
        /// <remarks/>
        public string GroupBackShowBN {
            get {
                return this.groupBackShowBNField;
            }
            set {
                this.groupBackShowBNField = value;
            }
        }
        
        /// <remarks/>
        public string GroupBackSoundBN {
            get {
                return this.groupBackSoundBNField;
            }
            set {
                this.groupBackSoundBNField = value;
            }
        }
        
        /// <remarks/>
        public string GroupBackZhiJingMaiBN {
            get {
                return this.groupBackZhiJingMaiBNField;
            }
            set {
                this.groupBackZhiJingMaiBNField = value;
            }
        }
        
        /// <remarks/>
        public string GroupBackSheXiangTouBN {
            get {
                return this.groupBackSheXiangTouBNField;
            }
            set {
                this.groupBackSheXiangTouBNField = value;
            }
        }
        
        /// <remarks/>
        public string PrinterName {
            get {
                return this.printerNameField;
            }
            set {
                this.printerNameField = value;
            }
        }
        
        /// <remarks/>
        public string[] BoxArray {
            get {
                return this.boxArrayField;
            }
            set {
                this.boxArrayField = value;
            }
        }
        
        /// <remarks/>
        public string[] GroupNameArray {
            get {
                return this.groupNameArrayField;
            }
            set {
                this.groupNameArrayField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.farshine.com/")]
    public partial class BoxSetInfoClass {
        
        private string boxNOField;
        
        private string frontBoxBNField;
        
        private bool hasTwoLockField;
        
        private string backBoxBNField;
        
        /// <remarks/>
        public string BoxNO {
            get {
                return this.boxNOField;
            }
            set {
                this.boxNOField = value;
            }
        }
        
        /// <remarks/>
        public string FrontBoxBN {
            get {
                return this.frontBoxBNField;
            }
            set {
                this.frontBoxBNField = value;
            }
        }
        
        /// <remarks/>
        public bool HasTwoLock {
            get {
                return this.hasTwoLockField;
            }
            set {
                this.hasTwoLockField = value;
            }
        }
        
        /// <remarks/>
        public string BackBoxBN {
            get {
                return this.backBoxBNField;
            }
            set {
                this.backBoxBNField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.farshine.com/")]
    public partial class FanWeiClass {
        
        private string yFBizoZhiField;
        
        private int receiveBoxNOField;
        
        private string showmsgField;
        
        private int countField;
        
        private bool isDeleteField;
        
        private bool isTouxiangField;
        
        private string sendTimeField;
        
        private int sendCountField;
        
        private bool isKanWuField;
        
        private string kanwuTimeField;
        
        private string kwAdminCardField;
        
        private string kwUserCardField;
        
        private bool isQuJianField;
        
        private string receiveTimeField;
        
        private string receiveUserCardField;
        
        /// <remarks/>
        public string YFBizoZhi {
            get {
                return this.yFBizoZhiField;
            }
            set {
                this.yFBizoZhiField = value;
            }
        }
        
        /// <remarks/>
        public int ReceiveBoxNO {
            get {
                return this.receiveBoxNOField;
            }
            set {
                this.receiveBoxNOField = value;
            }
        }
        
        /// <remarks/>
        public string Showmsg {
            get {
                return this.showmsgField;
            }
            set {
                this.showmsgField = value;
            }
        }
        
        /// <remarks/>
        public int Count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        public bool isDelete {
            get {
                return this.isDeleteField;
            }
            set {
                this.isDeleteField = value;
            }
        }
        
        /// <remarks/>
        public bool IsTouxiang {
            get {
                return this.isTouxiangField;
            }
            set {
                this.isTouxiangField = value;
            }
        }
        
        /// <remarks/>
        public string SendTime {
            get {
                return this.sendTimeField;
            }
            set {
                this.sendTimeField = value;
            }
        }
        
        /// <remarks/>
        public int SendCount {
            get {
                return this.sendCountField;
            }
            set {
                this.sendCountField = value;
            }
        }
        
        /// <remarks/>
        public bool IsKanWu {
            get {
                return this.isKanWuField;
            }
            set {
                this.isKanWuField = value;
            }
        }
        
        /// <remarks/>
        public string KanwuTime {
            get {
                return this.kanwuTimeField;
            }
            set {
                this.kanwuTimeField = value;
            }
        }
        
        /// <remarks/>
        public string KwAdminCard {
            get {
                return this.kwAdminCardField;
            }
            set {
                this.kwAdminCardField = value;
            }
        }
        
        /// <remarks/>
        public string KwUserCard {
            get {
                return this.kwUserCardField;
            }
            set {
                this.kwUserCardField = value;
            }
        }
        
        /// <remarks/>
        public bool IsQuJian {
            get {
                return this.isQuJianField;
            }
            set {
                this.isQuJianField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiveTime {
            get {
                return this.receiveTimeField;
            }
            set {
                this.receiveTimeField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiveUserCard {
            get {
                return this.receiveUserCardField;
            }
            set {
                this.receiveUserCardField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.farshine.com/")]
    public partial class YuFaClass {
        
        private string yFBizoZhiField;
        
        private string barcodeField;
        
        private string barcode56Field;
        
        private string fullBarcodeField;
        
        private bool isJiJianField;
        
        private int bartypeField;
        
        private int receiveBoxNOField;
        
        private string showmsgField;
        
        private int yuFaTypeField;
        
        private bool isTuiXinField;
        
        private string tuiXinUserIdField;
        
        private bool isDeleteField;
        
        private string yuFaTimeField;
        
        private string docIDField;
        
        private bool isTouxiangField;
        
        private string sendTimeField;
        
        private bool isJiaJiField;
        
        private string sendUserCardNOField;
        
        private string luXiangFileNameField;
        
        private bool isKanWuField;
        
        private string kanwuTimeField;
        
        private string kwAdminCardField;
        
        private string kwUserCardField;
        
        private bool isQuJianField;
        
        private string receiveTimeField;
        
        private string receiveUserCardField;
        
        private FanWeiClass[] fanWeiField;
        
        private int fenZuTouXiangFangShiField;
        
        /// <remarks/>
        public string YFBizoZhi {
            get {
                return this.yFBizoZhiField;
            }
            set {
                this.yFBizoZhiField = value;
            }
        }
        
        /// <remarks/>
        public string Barcode {
            get {
                return this.barcodeField;
            }
            set {
                this.barcodeField = value;
            }
        }
        
        /// <remarks/>
        public string Barcode56 {
            get {
                return this.barcode56Field;
            }
            set {
                this.barcode56Field = value;
            }
        }
        
        /// <remarks/>
        public string FullBarcode {
            get {
                return this.fullBarcodeField;
            }
            set {
                this.fullBarcodeField = value;
            }
        }
        
        /// <remarks/>
        public bool IsJiJian {
            get {
                return this.isJiJianField;
            }
            set {
                this.isJiJianField = value;
            }
        }
        
        /// <remarks/>
        public int Bartype {
            get {
                return this.bartypeField;
            }
            set {
                this.bartypeField = value;
            }
        }
        
        /// <remarks/>
        public int ReceiveBoxNO {
            get {
                return this.receiveBoxNOField;
            }
            set {
                this.receiveBoxNOField = value;
            }
        }
        
        /// <remarks/>
        public string Showmsg {
            get {
                return this.showmsgField;
            }
            set {
                this.showmsgField = value;
            }
        }
        
        /// <remarks/>
        public int YuFaType {
            get {
                return this.yuFaTypeField;
            }
            set {
                this.yuFaTypeField = value;
            }
        }
        
        /// <remarks/>
        public bool isTuiXin {
            get {
                return this.isTuiXinField;
            }
            set {
                this.isTuiXinField = value;
            }
        }
        
        /// <remarks/>
        public string TuiXinUserId {
            get {
                return this.tuiXinUserIdField;
            }
            set {
                this.tuiXinUserIdField = value;
            }
        }
        
        /// <remarks/>
        public bool isDelete {
            get {
                return this.isDeleteField;
            }
            set {
                this.isDeleteField = value;
            }
        }
        
        /// <remarks/>
        public string YuFaTime {
            get {
                return this.yuFaTimeField;
            }
            set {
                this.yuFaTimeField = value;
            }
        }
        
        /// <remarks/>
        public string DocID {
            get {
                return this.docIDField;
            }
            set {
                this.docIDField = value;
            }
        }
        
        /// <remarks/>
        public bool IsTouxiang {
            get {
                return this.isTouxiangField;
            }
            set {
                this.isTouxiangField = value;
            }
        }
        
        /// <remarks/>
        public string SendTime {
            get {
                return this.sendTimeField;
            }
            set {
                this.sendTimeField = value;
            }
        }
        
        /// <remarks/>
        public bool IsJiaJi {
            get {
                return this.isJiaJiField;
            }
            set {
                this.isJiaJiField = value;
            }
        }
        
        /// <remarks/>
        public string SendUserCardNO {
            get {
                return this.sendUserCardNOField;
            }
            set {
                this.sendUserCardNOField = value;
            }
        }
        
        /// <remarks/>
        public string LuXiangFileName {
            get {
                return this.luXiangFileNameField;
            }
            set {
                this.luXiangFileNameField = value;
            }
        }
        
        /// <remarks/>
        public bool IsKanWu {
            get {
                return this.isKanWuField;
            }
            set {
                this.isKanWuField = value;
            }
        }
        
        /// <remarks/>
        public string KanwuTime {
            get {
                return this.kanwuTimeField;
            }
            set {
                this.kanwuTimeField = value;
            }
        }
        
        /// <remarks/>
        public string KwAdminCard {
            get {
                return this.kwAdminCardField;
            }
            set {
                this.kwAdminCardField = value;
            }
        }
        
        /// <remarks/>
        public string KwUserCard {
            get {
                return this.kwUserCardField;
            }
            set {
                this.kwUserCardField = value;
            }
        }
        
        /// <remarks/>
        public bool IsQuJian {
            get {
                return this.isQuJianField;
            }
            set {
                this.isQuJianField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiveTime {
            get {
                return this.receiveTimeField;
            }
            set {
                this.receiveTimeField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiveUserCard {
            get {
                return this.receiveUserCardField;
            }
            set {
                this.receiveUserCardField = value;
            }
        }
        
        /// <remarks/>
        public FanWeiClass[] FanWei {
            get {
                return this.fanWeiField;
            }
            set {
                this.fanWeiField = value;
            }
        }
        
        /// <remarks/>
        public int FenZuTouXiangFangShi {
            get {
                return this.fenZuTouXiangFangShiField;
            }
            set {
                this.fenZuTouXiangFangShiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetGuiZeListCompletedEventHandler(object sender, GetGuiZeListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGuiZeListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGuiZeListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GuiZeListClass[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GuiZeListClass[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetYuFaInfoCompletedEventHandler(object sender, GetYuFaInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetYuFaInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetYuFaInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public YuFaClass[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((YuFaClass[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void SendYuFaInfoCompletedEventHandler(object sender, SendYuFaInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendYuFaInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendYuFaInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public YuFaClass infos {
            get {
                this.RaiseExceptionIfNecessary();
                return ((YuFaClass)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetBoxSetInfoCompletedEventHandler(object sender, GetBoxSetInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBoxSetInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBoxSetInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BoxSetInfoClass[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BoxSetInfoClass[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetGroupSetInfoCompletedEventHandler(object sender, GetGroupSetInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGroupSetInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGroupSetInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GroupSetInfoClass[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GroupSetInfoClass[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetAllBoxInfoCompletedEventHandler(object sender, GetAllBoxInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllBoxInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllBoxInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BoxInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BoxInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetBoxShowMessageCompletedEventHandler(object sender, GetBoxShowMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBoxShowMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBoxShowMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ClassBoxShowMessage[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ClassBoxShowMessage[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetAllCardInfoCompletedEventHandler(object sender, GetAllCardInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllCardInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllCardInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CardInfoClass[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CardInfoClass[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetBarcodeMuBanListCompletedEventHandler(object sender, GetBarcodeMuBanListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBarcodeMuBanListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBarcodeMuBanListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ClassBarcodeMuBanList[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ClassBarcodeMuBanList[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetMuBanInfoCompletedEventHandler(object sender, GetMuBanInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMuBanInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMuBanInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public YuFaClass Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((YuFaClass)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void SendBoxStatusCompletedEventHandler(object sender, SendBoxStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendBoxStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendBoxStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void UserGetLetterCompletedEventHandler(object sender, UserGetLetterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserGetLetterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserGetLetterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void UserGetLetter_RecordCompletedEventHandler(object sender, UserGetLetter_RecordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserGetLetter_RecordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserGetLetter_RecordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void UserGetLetter_SetPicCompletedEventHandler(object sender, UserGetLetter_SetPicCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserGetLetter_SetPicCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserGetLetter_SetPicCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void UserGetLetter_ReportCompletedEventHandler(object sender, UserGetLetter_ReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserGetLetter_ReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserGetLetter_ReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserGetLetterReturnClass Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserGetLetterReturnClass)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void PrintUserReturnLetterCompletedEventHandler(object sender, PrintUserReturnLetterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PrintUserReturnLetterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PrintUserReturnLetterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserGetLetterReturnClass Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserGetLetterReturnClass)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591